# Generated by Django 3.1.2 on 2020-10-28 08:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Attribute',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('conf', models.CharField(default='', max_length=200)),
                ('value', models.CharField(default='', max_length=200)),
                ('key', models.CharField(default='', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deviceId', models.CharField(max_length=200)),
                ('deviceName', models.CharField(max_length=200)),
                ('personId', models.CharField(max_length=200)),
                ('personName', models.CharField(max_length=200)),
                ('attributes', models.ForeignKey(blank=True, default='', on_delete=django.db.models.deletion.CASCADE, related_name='attributes', to='pelion.attribute')),
            ],
        ),
    ]
